### ISSUE TITLE
Travis CI build error: bad argument

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma.com#32]
I’m not sure what’s the cause, as the message is a bit cryptic:

https://travis-ci.com/riboseinc/metanorma.com/builds/90256237

```
jekyll 3.8.4 | Error:  bad argument (expected URI object or URI string)
rake aborted!
Command failed with status (1): [JEKYLL_ENV=production jekyll build --confi...]
/home/travis/build/riboseinc/metanorma.com/Rakefile:65:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => test:production => build:production
(See full trace by running task with --trace)
```

@ronaldtse could you help or refer someone?

**Comment by strogonoff** [comment]
Latest build works on my machine as usual, but www.metanorma.com doesn’t seem to get updated after a few recent pushes

**Comment by strogonoff** [comment]
Going to try updating Rakefile with `bundle exec` in front of Jekyll build

**Comment by strogonoff** [comment]
Issue identified:

```
bundler: failed to load command: jekyll (/Users/tony/.rvm/gems/ruby-2.4.4/bin/jekyll)
ArgumentError: bad argument (expected URI object or URI string)
  /Users/tony/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/uri/common.rb:739:in `URI'
  /Volumes/Ribose/jekyll-theme-open-project-helpers/lib/jekyll-theme-open-project-helpers/external_links.rb:16:in `block in <top (required)>'                                                              
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-3.8.4/lib/jekyll/hooks.rb:103:in `block in trigger'
  /Users/tony/.rvm/gems/ruby-2.4.4/gems/jekyll-3.8.4/lib/jekyll/hooks.rb:102:in `each'
```
